project:
    name: airflow
    volumes:
        - host: /.backup
          container: /usr/local/airflow/backup
        - host: C:\Users\henri\OneDrive\Documents\Projetos\Airflow\carteira_dbt_airflow
          container: /usr/local/airflow/carteira_dbt_airflow
