name: Airflow Dags Check

on:
  push:
    branches:
      - "**"
    workflow_dispatch:

jobs:
  airflow_dag_check:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install apache-airflow==2.10.5 apache-airflow-providers-common-sql
            pip install psycopg2-binary
            pip install asyncpg
            pip install apache-airflow-providers-postgres

        - name: Install requirements
          run: pip install -r requirements.txt

        - name: Init airflow db
          run: |
            airflow db init

        - name: Create Mockup PROD connection
          run: |
            airflow connections add local_pg \
            --conn-type postgres \
            --conn-host mockup \
            --conn-login login \
            --conn-password password \
            --conn-schema mockup_db

        - name: Create Mockup STG connection
          run: |
            airflow connections add local_pg_stg \
            --conn-type postgres \
            --conn-host mockup \
            --conn-login login \
            --conn-password password \
            --conn-schema mockup_db

        - name: Check Dags for errors
          run: |
            python check_dags.py
