name: Dbt Tests

on:
    push:
      branches:
        - '**'
    workflow_dispatch:

jobs:
    dbt_checks:
      runs-on: ubuntu-latest

      steps:
          - name: Check repo
            uses: actions/checkout@v4

          - name: set Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.12'
          - name: install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install dbt-core dbt-postgres 

          - name: fetch Profiles.yml
            run: | 
              mkdir -p ~/.dbt
              echo "${{ secrets.PROFILES_YML }}" > ~/.dbt/profiles.yml
              

          - name: Check installation
            run: |
                cd carteira_dbt_airflow
                dbt debug --config-dir

          - name: Validate syntax of models
            run : |
              cd carteira_dbt_airflow
              dbt parse
              


